### ISSUE TITLE
If Pier is malicious, how can relay-chain recognize it?

### ISSUE THREAD

**Issue by terasum** [meshplus/bitxhub#10]
## General Question
When I read the White-Paper, I found a question about the Pier design.
Compare with Cosmos and Plokadot, those design both ensure the protocol communicate with relay-chain directly, but Bitxhub use the Pier to achieve this.

I wonder if the Pier is malicious, can relay-chain recognize this? Just by the source appChain's Merkle Proof? How about a Pier makes a fake proof?

In the section 5 of the White-Paper, has addressed the basic solution about prevent malicious Pier, but I'm doubt how can a dozen of Pires reach a agreement to confirm a transaction, by some consensus algorithm?

**Comment by 4ever9** [comment]
Neither cosmos nor polkadot can communicate with relaychain directly and they all need an intermediary(called relayer in cosmos and collator in polkadot).

Pier is only responsible for the collection and forwarding of interchain transactions and collection of `proof`. When an appchain joins the bitxhub, it's validator information needs to be registered in bitxhub. The `proof` contains validator signatures, so bitxhub can detect the fake `proof`.

**Comment by terasum** [comment]
@4ever9 Ok, got it. Further more, if Pier cannot verify the proof, how can Pier ensure the validator is true? The validator's identify also need Bitxhub to verify? Means that the register process should contain the validator's identity?

**Comment by 4ever9** [comment]
Yes.The BitXHub will audit the registration information (contains validator identify) after appchain registering to bitxhub.

**Comment by terasum** [comment]
Thanks, so, how does Bitxhub audit the validators, by plugins?
