### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by GrapeBaBa** [meshplus/bitxhub#11]
## Bug Report

build error

### 1. What did you do?

`
kaichen@Kais-MacBook-Pro bitxhub % bash scripts/prepare.sh
===> 1. Install packr
go: finding github.com/meshplus/bitxhub-kit v0.0.0-20200329124935-585edb85ca63
go: github.com/meshplus/bitxhub-kit@v0.0.0-20200329124935-585edb85ca63: unknown revision 585edb85ca63
go: error loading module requirements
===> 2. Install golangci-lint
go: finding github.com/meshplus/bitxhub-kit v0.0.0-20200329124935-585edb85ca63
go: github.com/meshplus/bitxhub-kit@v0.0.0-20200329124935-585edb85ca63: unknown revision 585edb85ca63
go: error loading module requirements
===> 3. Install go mock tool
go: finding github.com/meshplus/bitxhub-kit v0.0.0-20200329124935-585edb85ca63
go: github.com/meshplus/bitxhub-kit@v0.0.0-20200329124935-585edb85ca63: unknown revision 585edb85ca63
go: error loading module requirements
`

### 2. What did you expect to see?
build success
### 3. What did you see instead?
error above
### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)
master branch

**Comment by 4ever9** [comment]
Fixed: https://github.com/meshplus/bitxhub/pull/12
