### ISSUE TITLE
Bitxhub got paniced when invoke xvm contract

### ISSUE THREAD

**Issue by Alexader** [meshplus/bitxhub#125]
### 1. What did you do?

After i was testing for xvm contract, i want to invoke the inserted  StoreContract like this:
![image](https://user-images.githubusercontent.com/20707238/88374646-a4cad480-cdcc-11ea-8bbc-afe03c034400.png)

### 2. What did you expect to see?
Contract invoke should return failed receipt.

### 3. What did you see instead?

Bitxhub got paniced.
![image](https://user-images.githubusercontent.com/20707238/88374716-ce83fb80-cdcc-11ea-869b-4a4f40533ca3.png)

### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)
Commit hash: 9ae5793

**Comment by levi9311** [comment]
It is a bug in bitxhub-kit. I move this issue to [here](https://github.com/meshplus/bitxhub-kit/issues/12#issue-666008532).
