### ISSUE TITLE
How can I implement BitXHub with GM crypto?

### ISSUE THREAD

**Issue by lghhh** [meshplus/bitxhub#127]
## General Question
I have implemented Fabric with GM crypto. If I want to use BitXhub for intercommunication, what modifications should I do?

**Comment by jzhe886** [comment]
Thank you for your question, you should modify the fabric verification rules and use the GM algorithm to verify the certificate of the fabric endorsement node.
You can refer to the verification rule: [code the verification rule](https://github.com/meshplus/bitxhub/wiki/%E9%AA%8C%E8%AF%81%E5%BC%95%E6%93%8E%E8%A7%84%E5%88%99%E7%BC%96%E5%86%99)
