### ISSUE TITLE
Send tx with wrong private key's signature should fail, but not.

### ISSUE THREAD

**Issue by treasersimplifies** [meshplus/bitxhub#128]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

Send tx with wrong private key's signature , but not.

### 2. What did you expect to see?

The receipt of the tx should be `Receipt_FAILED`.

### 3. What did you see instead?

The receipt of the tx should is `Receipt_SUCCESS`.

```
=== RUN   TestTester/TestTXWrongSigPrivateKey
    TestTester/TestTXWrongSigPrivateKey: case009_transaction_test.go:82: 
                Error Trace:    case009_transaction_test.go:82
                Error:          Should be true
                Test:           TestTester/TestTXWrongSigPrivateKey
--- FAIL: TestTester (17.20s)
```

### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)

```
BitXHub version: 1.0.0-rc1-master-7a00eb3
App build date: 2020-07-27T14:05:37
System version: darwin/amd64
Golang version: go1.14.4
```

**Comment by Alexader** [comment]
Fixed by #133
