### ISSUE TITLE
Register rule with unexisted contract address should fail, but not.

### ISSUE THREAD

**Issue by treasersimplifies** [meshplus/bitxhub#129]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

Register rule with unexisted contract address

### 2. What did you expect to see?

The receipt of the tx should be `Receipt_FAILED`.

### 3. What did you see instead?

The receipt of the tx should is `Receipt_SUCCESS`.

```
=== RUN   TestTester/TestRegisterUnexistedWasmRuleShouldFail
    TestTester/TestRegisterUnexistedWasmRuleShouldFail: case008_rule_test.go:90: 
                Error Trace:    case008_rule_test.go:90
                Error:          Expected value not to be nil.
                Test:           TestTester/TestRegisterUnexistedWasmRuleShouldFail
    TestTester/TestRegisterUnexistedWasmRuleShouldFail: case008_rule_test.go:91: 
                Error Trace:    case008_rule_test.go:91
                Error:          Should be true
                Test:           TestTester/TestRegisterUnexistedWasmRuleShouldFail
```

### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)

```
BitXHub version: 1.0.0-rc1-master-7a00eb3
App build date: 2020-07-27T14:05:37
System version: darwin/amd64
Golang version: go1.14.4
```

**Comment by dawn-to-dusk** [comment]
邮件已收到，谢谢啦~

**Comment by treasersimplifies** [comment]
Hi there,Thank you for your email. I am currently offline and will not have access to email instantly. If this is urgent, please contact me by phone 18258583270. I will do my best to respond promptly to your email when I am on line.Best,
