### ISSUE TITLE
The Fabric-SDK-Go in the fabric-cli is not a stable version

### ISSUE THREAD

**Issue by lghhh** [meshplus/bitxhub#139]
## Bug Report

The Fabric-SDK-Go in the fabric-cli is not a stable version (https://github.com/securekey/fabric-examples/blob/master/fabric-cli/cmd/fabric-cli/go.mod)，which is incompatible with all stable versions of fabric-sdk. It's hard to modify to match current fabric networks.
![image](https://user-images.githubusercontent.com/23379305/89727515-3d618580-da58-11ea-8d4e-316dfd5080cb.png)
![image](https://user-images.githubusercontent.com/23379305/89727529-64b85280-da58-11ea-8546-ff3b21e898c8.png)
v1.0.0-beta1 and v1.0.0-beta2 are both wrong.

### 1. What did you do?
Modify the version of fabric-sdk-go to v1.0.0-beta1, then start ffn.sh, install chaincode.sh.

### 2. What did you expect to see?
Everything goes well.

### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)
v1.0.0-rc1

**Comment by jzhe886** [comment]
Thank you for your feedback. The fabric-cli tool is to facilitate developers to deploy contracts and call contracts. 
If in the actual production environment, it is recommended to use the tools that come with fabric.
