### ISSUE TITLE
Query IBTP commnad

### ISSUE THREAD

**Issue by 4ever9** [meshplus/bitxhub#141]
## Development Task

Add a command that queries ibtp by id.

```
bitxhub client ibtp get <ibtp-id>
```

**Comment by jzhe886** [comment]
小提示：
1. 新建cmd/bitxhub/client/ibtp.go文件；
2. 在`ibtpCMD()`的`Subcommands`添加`get`命令；
3. `get`函数中通过`sendTx`的方式向bitxhub发送查询IBTP的交易；
4. 将交易回执以json格式进行解析；
