### ISSUE TITLE
Send transaction command

### ISSUE THREAD

**Issue by 4ever9** [meshplus/bitxhub#142]
## Development Task

There are a series of subcommands about this task:

- [ ] 1. Transfer

Example:
```
bitxhub client tx send --path <private_key_path> --to 0x111111111 --amount 100
```

- [ ] 2. Invoke contract

Example:

```
bitxhub client tx invoke --path <private_key_path> --to <contract_address> --function get --params string,arg1 --params uint64,arg2
```

**Comment by jzhe886** [comment]
小提示：
1. 代码逻辑在cmd/bitxhub/client/transaction.go文件；
2. 添加`txCMD()`的`Subcommands`添加`invoke`命令；
3. `invoke`函数中通过`sendTx`的方式向bitxhub发送调用合约的交易；
4. 将交易回执以json格式进行解析；
