### ISSUE TITLE
Network problem and and some document optimization suggestions

### ISSUE THREAD

**Issue by LiYang27** [meshplus/bitxhub#155]
## General Question
When I tried to use it based on Quick Start. Because of the network, when executing the command: bash ffn.sh up, the Docker image could not be downloaded. It is recommended to indicate in the document that Docker can switch the mirror source, which is more user-friendly.
When the command bash chaincode.sh install is executed and the VPN is turned on (I can access google, but the speed is very slow), a long wait occurs, and the following error occurs eventually. 
![image](https://user-images.githubusercontent.com/16488169/92063061-cd32ef00-edcc-11ea-9751-540007bc9775.png)
        <center>Fig. 1 A long wait occurs </center>

![image](https://user-images.githubusercontent.com/16488169/92064151-7c70c580-edcf-11ea-912a-1ed29035bc20.png)
        <center>Fig. 2 An Error </center>
I guess it may be due to the timeout of golang related downloads. But in my current network environment, I don't know how to solve this problem.

## Some Advices

1. I recommend Bitxhub can be optimized for different network environments, and thus more suitable for Chinese developers and users.
2.  In the wiki documentation, it seems that there is no documentation for pier cmd (such as pier --repo) and BitxHub cmd. Adding guidance may make getting started easier.
3. In the BitXHub white paper, it is mentioned that "To ensure the reliability of Piers, incentives and punishments are adopted.", I think it is possible to clarify how to implement rewards and punishments, which may improve the reliability of BitXHub.

**Comment by jzhe886** [comment]
1. for your network environments, if you turn on VPN:
```
export http_proxy=http://127.0.0.1:port
export https_proxy=http://127.0.0.1:port
```
2. you can access pier's github to read [wiki doc](https://github.com/meshplus/pier/wiki/Pier%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3)
3. For the alliance chain scenario, the incentives and penalties for Pier are not very important, and the deployment of Pier is maintained by relevant agencies
