### ISSUE TITLE
Bloom filter persistence error

### ISSUE THREAD

**Issue by 4ever9** [meshplus/bitxhub#16]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

Send tx to BitXHub.

### 3. What did you see instead?

![image](https://user-images.githubusercontent.com/29200902/79358015-4c856a80-7f73-11ea-86fb-1e505bf00a6d.png)

### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)

```
$ bitxhub version

BitXHub version: 1.0.0-rc1-master-e3a4b44
App build date: 2020-04-15T23:34:41
System version: darwin/amd64
Golang version: go1.13.8
```

**Comment by jzhe886** [comment]
May be remove the log file can cause this problem.
