### ISSUE TITLE
Sth worry in Deploy Interchain Contract

### ISSUE THREAD

**Issue by bigrance** [meshplus/bitxhub#227]
## General Question
In quick start ,when i execute to bash chaincode.sh install , it says that:
![image](https://user-images.githubusercontent.com/69037827/97328148-af57a700-18b0-11eb-839e-95a7956e784e.png)
![image](https://user-images.githubusercontent.com/69037827/99508414-844c0900-29bf-11eb-91e2-bef711ec130b.png)

and in https://github.com/hyperledger/fabric-sdk-go/  it says that :
![image](https://user-images.githubusercontent.com/69037827/97381153-6d0b8580-1903-11eb-86e1-c90d5f6b3dc7.png)

and i opened chaincode.sh , when executed to go get "github.com/securekey/fabric-examples/fabric-cli/cmd/fabric-cli",it said that:
![image](https://user-images.githubusercontent.com/69037827/97415414-28520f80-1940-11eb-99ce-3f79dd2c3078.png)

what should i do

**Comment by Alexader** [comment]
What version of go are you using? Its recommended to use go1.1.3 and above.

**Comment by bigrance** [comment]
the go i used  was  1.15

**Comment by levi9311** [comment]
> the go i used was 1.15

What is ur go env?

**Comment by bigrance** [comment]
> > the go i used was 1.15
> 
> What is ur go env? Do you set ”GO111MODULE=on“

oh,i didn't! let we try again

**Comment by bigrance** [comment]
> > the go i used was 1.15
> 
> What is ur go env? Do you set ”GO111MODULE=on“

it's all right now, but another error occured,it says that:
===> 2. Set Alice 10000 amout in transfer chaincode
*** 0 successfull invocation(s) out of 1
*** 0 successfull invocation(s) out of 1
*** 0 successfull invocation(s) out of 1
*** 0 successfull invocation(s) out of 1

**Comment by bigrance** [comment]
what should i do?
