### ISSUE TITLE
cp: cannot stat '/root/goproj/src/github.com/meshplus/pier-client-fabric/build/fabric-client-1.4.so': No such file or directory

### ISSUE THREAD

**Issue by bolenzhang** [meshplus/bitxhub#254]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

执行bash fabric_pier.sh start -r '.pier' -c 'crypto-config'  -g 'config.yaml' -p 8987 -b 'localhost:60011' -o 44555

### 2. What did you expect to see?
顺利部署跨链网关

### 3. What did you see instead?
cp: cannot stat '/root/goproj/src/github.com/meshplus/pier-client-fabric/build/fabric-client-1.4.so': No such file or directory

### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)
BitXHub version: 1.0.0-rc1-HEAD-8d24681
App build date: 2020-11-18T14:58:03
System version: linux/amd64
Golang version: go1.14.2

### others
补充，追了下fabric_pier.sh，是因为pier-client-fabric在make fabric1.4的时候没有生成.so动态链接库文件，生成的是fabric-client-1.4的可执行文件，继而看pier-client-fabric的Makefile，发现make fabric1.4压根儿也不会生成.so文件啊，*.go中也没import C，export func之类的。
你们的quick start demo根本无法跑通啊。

**Comment by jzhe886** [comment]
请问pier-client-fabric的版本是v1.0.0-rc1吗？fabric_pier.sh是会切到v1.0.0-rc1的。

**Comment by bolenzhang** [comment]
> 请问pier-client-fabric的版本是v1.0.0-rc1吗？fabric_pier.sh是会切到v1.0.0-rc1的。
之前本地是v1.1.0-rc1分支，我看了下1.0.0-rc1的Makefile没问题，1.1.0的有问题。

**Comment by jzhe886** [comment]
v1.1.0的pier-client-fabric采用的不是go原生支持的插件形式，而是生成的可执行文件，需要配套pier v1.1.0才可使用。
目前quick start中支持的都是v1.0.0-rc1，包括中继链，跨链网关以及跨链网关插件。
