### ISSUE TITLE
invoke bvm contract: send tx error:

### ISSUE THREAD

**Issue by bigrance** [meshplus/bitxhub#258]
## General Question
在执行quick start的时候，执行到启动跨链网关这一步中的bash fabric_pier.sh start -r '.pier' -c 'crypto-config'  -g 'config.yaml' -p 8987 -b 'localhost:60011' -o 44555命令时，总会出现：
![image](https://user-images.githubusercontent.com/69037827/99895841-b44c2280-2cc5-11eb-8426-56388c89d629.png)
也就是invoke bvm contract: send tx error: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:60011: connect: connection refused"
这样的错误，请问是什么原因呢？
这是四个节点的启动情况：
![image](https://user-images.githubusercontent.com/69037827/99896096-2a518900-2cc8-11eb-866f-4f5a1a39c0cc.png)

**Comment by bigrance** [comment]
我又试了一下，在单节点模式下可以，多节点就不行了，就会出现上述错误

**Comment by levi9311** [comment]
从截图来看是raft插件版本不一致，所以节点没有启动成功。

**Comment by bigrance** [comment]
> 从截图来看是raft插件版本不一致，所以节点没有启动成功。

只有在单节点solo模式下能够启动成功，多节点就会失败

**Comment by levi9311** [comment]
单节点情况下不会用到共识，所以启动可以成功的，你这边raft插件是怎么编译的

**Comment by bigrance** [comment]
> 单节点情况下不会用到共识，所以启动可以成功的，你这边raft插件是怎么编译的

我就是好奇为啥raft共识不行，我就是按照quickstart上说的一步步来的，make cluster这个命令

**Comment by bigrance** [comment]
> 单节点情况下不会用到共识，所以启动可以成功的，你这边raft插件是怎么编译的


> 单节点情况下不会用到共识，所以启动可以成功的，你这边raft插件是怎么编译的

我就是好奇为啥raft共识不行，我是按照去quickstart上一步步来的

> 单节点情况下不会用到共识，所以启动可以成功的，你这边raft插件是怎么编译的

前面所有命令并没有报错，我的go，docker都是最新版本，然后系统是Ubuntu18

**Comment by jzhe886** [comment]
我这边make cluster是正常的，请用git status 看看是否有改动代码文件。
![image](https://user-images.githubusercontent.com/17755623/99899632-c9d14480-2ce5-11eb-90e0-394bc7d302fc.png)

**Comment by bigrance** [comment]
> 我这边make cluster是正常的，请用git status 看看是否有改动代码文件。
> ![image](https://user-images.githubusercontent.com/17755623/99899632-c9d14480-2ce5-11eb-90e0-394bc7d302fc.png)
> 
> > > 单节点情况下不会用到共识，所以启动可以成功的，你这边raft插件是怎么编译的
> > 
> > 
> > > 单节点情况下不会用到共识，所以启动可以成功的，你这边raft插件是怎么编译的
> > 
> > 
> > 我就是好奇为啥raft共识不行，我是按照去quickstart上一步步来的
> > > 单节点情况下不会用到共识，所以启动可以成功的，你这边raft插件是怎么编译的
> > 
> > 
> > 前面所有命令并没有报错，我的go，docker都是最新版本，然后系统是Ub
这是他返回的结果：
root@iZj6chf4qqoc00k0ms6uguZ:~/bitxhub# git status 
HEAD detached at v1.0.0-rc1
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   go.mod
        modified:   go.sum

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by levi9311** [comment]
插件和BitXub二进制编译是在一个目录下吗

**Comment by levi9311** [comment]
插件和BitXub二进制编译是在一个目录下吗

**Comment by bigrance** [comment]
> 插件和BitXub二进制编译是在一个目录下吗
我先进入bitxhub，执行了bash scripts/prepare.sh，然后在bitxhub下执行make

**Comment by levi9311** [comment]
插件和BitXub二进制编译是在一个目录下吗

**Comment by bigrance** [comment]
> 插件和BitXub二进制编译是在一个目录下吗
应该不会出现不在一个目录的情况？我先安装了tmux，然后下载bitxhub到根目录,进入bitxhub后,执行git checkout v1.0.0-rc1，会提示如下：
Note: checking out 'v1.0.0-rc1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>
然后在当前目录执行bash scripts/prepare.sh 
接着在当前目录执行make cluster
步骤应该没有问题呀

**Comment by bigrance** [comment]
> 插件和BitXub二进制编译是在一个目录下吗

应该不会出现不在一个目录的情况？我先安装了tmux，然后下载bitxhub到根目录,进入bitxhub后,执行git checkout v1.0.0-rc1，会提示如下：
Note: checking out 'v1.0.0-rc1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

git checkout -b
然后在当前目录执行bash scripts/prepare.sh
接着在当前目录执行make cluster
步骤应该没有问题呀

**Comment by Alexader** [comment]
请确认一下运行 `make cluster` 命令的时候，下图处编译插件的步骤有没有出现报错。
![image](https://user-images.githubusercontent.com/20707238/99902452-eaef6080-2cf8-11eb-89b3-8a1b1f005a3d.png)

**Comment by bigrance** [comment]
> make cluster

突然就好了，我也不知道怎么回事，还是感谢三位大佬了

**Comment by jzhe886** [comment]
plz close this issue, tks!
