### ISSUE TITLE
关于启动跨链网关出现的问题

### ISSUE THREAD

**Issue by wangbaiqi355920251** [meshplus/bitxhub#285]
Golang version: go1.15.6
fabric 1.4.3
系统：腾讯云centos 7

根据快速开始教程到启动跨链网关部分，执行命令
bash fabric_pier.sh start -r '.pier' -c 'crypto-config'  -g 'config.yaml' -p 8987 -b 'localhost:60011' -o 44555
报错：
appchain client create: create channel fabcli fail: event service creation failed: could not get chConfig cache reference: QueryBlockConfig failed: queryChaincode failed: Transaction processing for endorser [localhost:10051]: Endorser Client Status Code: (2) CONNECTION_FAILED. Description: dialing connection timed out [localhost:10051]

希望作者解答一下，谢谢

**Comment by wangbaiqi355920251** [comment]
执行命令
bash fabric_pier.sh start -r '.pierB' -c 'crypto-configB'  -g 'configB.yaml' -p 8988 -b 'localhost:60011' -o 44556
则无报错运行

**Comment by Alexader** [comment]
请检查一下机器上是否正在运行如下图的容器，看报错是跨链网关启动时去连接fabric节点时网络连接出错
![image](https://user-images.githubusercontent.com/20707238/102456476-2bce6100-407c-11eb-8392-9b6faff9739d.png)

**Comment by wangbaiqi355920251** [comment]
感谢作者，问题已经解决
