### ISSUE TITLE
'make cluster' caused 'server exited unexpectedly'

### ISSUE THREAD

**Issue by 4ever9** [meshplus/bitxhub#3]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

When I run `make cluster`,  I found the error.

### 3. What did you see instead?

```
$ tmux ls
no server running on /private/tmp/tmux-501/default


$ make cluster
===> Staring cluster
server exited unexpectedly
make: *** [cluster] Error 1
```

### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)

```
$ bitxhub version

BitXHub version: 1.0.0-rc1-master-3d318a6
App build date: 2020-04-02T19:37:20
System version: darwin/amd64
Golang version: go1.13.8
```

**Comment by levi9311** [comment]
Now, there is something wrong with tmux version above 3.0 on Mac OS. Recommend using tmux version 2.9 instead.
See [https://github.com/tmux/tmux/issues/2111](https://github.com/tmux/tmux/issues/2111)
