### ISSUE TITLE
go 1.16版本下，编译的bitxhub可执行程序，启动后panic。

### ISSUE THREAD

**Issue by GreatMartial** [meshplus/bitxhub#338]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
golang 1.16下，在克隆到本地的bitxhub文件夹内，执行 bash scripts/prepare.sh安装工具。
执行make cluster。

### 3. What did you see instead?
执行make cluster，编译成功后，启动cluster时，log提示启动grpc端口后，会报panic（“无效的内存地址或索引”）。

本人通过更换golang版本到1.15.8，问题已解决。
### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)
BitXHub version: 1.0.0-rc1-HEAD-8d24681
App build date: 2021-02-19T13:43:16
System version: linux/amd64
Golang version: go1.16

**Comment by jzhe886** [comment]
谢谢反馈，目前暂不支持go1.16版本，下个版本会加强对go新版本的支持
