### ISSUE TITLE
about use "bash chaincode.sh install" will show "chaincode.sh: line 102: fabric-cli: command not found"

### ISSUE THREAD

**Issue by yan0327** [meshplus/bitxhub#341]
## General Question
我翻看了bitxhub的issue都没有人咨询这个问题，于是另外提出一个问题请教一下。具体表现为：
**[root@iZwz94l2kx809zxytqzn8sZ hyperledger]# bash chaincode.sh install
===> Install fabric-cli
go: github.com/securekey/fabric-examples/fabric-cli/cmd/fabric-cli upgrade => v0.0.0-20200123153516-600b6db41b10
===> Install chaincode
===> 1. Deploying broker, transfer and data_swapper chaincode
chaincode.sh: line 102: fabric-cli: command not found**

我在这之前已经安装了go 、docker等一系列工具。
首先下载fabric网络部署脚本，然后可以正常运行bash ffn.sh down和bash ffn.sh up。目录也有对应的文件夹，但是每当我执行bash chaincode.sh install就会出现上述异常。
PS：我尝试去github的fabric cli仓库直接clone下来下载，但是make失败。此外，我又从其他渠道去下载，也只能使用fabric的指令而不能使用fabric-cli的指令。

**Comment by jzhe886** [comment]
首先判断是否配置$GOPATH 和 $GOBIN，保证fabric-cli在$GOBIN可执行。

可以通过下面命令安装 fabric-cli:
```
go get github.com/securekey/fabric-examples/fabric-cli/cmd/fabric-cli
```

**Comment by yan0327** [comment]
已经解决了，非常感谢解答！
