### ISSUE TITLE
Transaction/state syncing for specified appchains

### ISSUE THREAD

**Issue by sandyzhou** [meshplus/bitxhub#403]
Implement the sync protocol to sync transaction and state data for some specified appchains.

**Comment by jzhe886** [comment]
## 描述
中继链数据节点（即不参与共识只同步数据的节点）可以进行配置，使其仅同步指定应用链相关的交易、状态、回执等数据。

## 标准
1. 接口设计清晰
2. 完善的单元测试
3. 必要的功能使用文档

## 赛题解读
联盟链中针对某条应用链的审计场景，审计机构需要获取该应用链的所有跨链交易和跨链数据，但是又不能随意访问其他应用链的数据，因此需要实现针对指定应用链的数据同步协议。

## 解题思路
分为节点配置和数据同步两个步骤。
1. 节点配置：节点配置需在链上进行，即需要将配置的节点信息同步到所有节点，其中包括节点的IP、端口、指定的应用链等信息。该步骤需要提交提案，并由管理员投票通过才能生效。
2. 数据获取：数据节点向至少quorum（根据共识节点个数和共识算法决定）个其他节点请求中继链的所有区块头数据、应用链相关的交易、状态、回执数据，并将获取的数据进行比较，只有获取到quorum个相同的数据，才将该数据存到本地；提供数据的节点需要检查请求数据的节点是否拥有所请求应用链的访问权限，只有拥有访问权限，该节点才能提供相应的数据。

## 参考
https://github.com/ethereum/go-ethereum/tree/master/eth/downloader
