### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by Ice-Storm** [meshplus/bitxhub#437]
## General Question

请教一下，当我两个组织各只有一个端口可以对外时该如何配置我们的网络结构呢？libp2p是如何支持根据不同类似节点的标识进行路由的呢？

**Comment by jzhe886** [comment]
非常感谢你的提问，现解答如下：

1. 通过下面命令生成libp2p的pid标识:
```
bitxhub cert priv gen --name node --target ~/.bitxhub
```
2. 查看libp2p的pid标识：
```
bitxhub cert priv pid --path ~/.bitxhub/node.priv
```
显示 _QmSpatgKBRoheXtoernNBpKXh4VAG261PMtjFQQyXs123F_，通过该pid标识在network.toml中配置IP+端口，示例如下：
```
hosts = ["/ip4/0.0.0.0/tcp/4001/p2p/"]
id = 1
pid = "QmSpatgKBRoheXtoernNBpKXh4VAG261PMtjFQQyXs123F"
```

**Comment by Ice-Storm** [comment]
当我这样配置后是否可以用nginx做代理呢？比如我一个组织有两个节点，但是出口nginx只能开放一个端口，如何进行网络配置呢？ @jzhe886 麻烦解答一下

**Comment by jzhe886** [comment]
bitxhub各个组织节点之间要保证能互相连接，不能通过nginx做端口代理
