### ISSUE TITLE
Get block header

### ISSUE THREAD

**Issue by jzhe886** [meshplus/bitxhub#485]
## Development Task
Get block header
```
bitxhub client header --height 110
```

**Comment by jzhe886** [comment]
小提示：
1. 代码逻辑在cmd/bitxhub/client/block.go文件；
2. 添加`blockCMD()`的`Subcommands`添加`getHeader`命令；
3. `getHeader`函数中通过`http get`的方式向url为`block_headers?start=%d&end=%d`发送请求；
4. 将返回值以json格式进行解析；

**Comment by Karenlrx** [comment]
finished
