### ISSUE TITLE
启动不成功

### ISSUE THREAD

**Issue by Sunyangyang12** [meshplus/bitxhub#520]
goduck playground start，报错 ：unsupport verison

**Comment by jzhe886** [comment]
请重新执行`goduck init`

**Comment by Sunyangyang12** [comment]
> 请重新执行`goduck init`
这是我操作的结果：，好像是不支持启动
root@iZj:~# goduck init
GoDuck configuration file already exists
reinitializing would overwrite your configuration, Y/N?
Y
root@iZ:~# goduck playground start
unsupport verison
root@iZ:~# goduck init
GoDuck configuration file already exists
reinitializing would overwrite your configuration, Y/N?
Y
root@iZ:~# goduck playground start
unsupport verison

**Comment by jzhe886** [comment]
请提供`goduck version`相关的信息，
删除`rm -rf ~/.goduck相关数据，拉取最新的goduck代码重新执行`goduck init`。

**Comment by Sunyangyang12** [comment]
> 请提供`goduck version`相关的信息。
> tips:删除`rm -rf ~/.goduck`相关数据，拉取最新的goduck代码重新执行`goduck init`。
非常感谢您，还是报错--不支持bitxhub版本

**root@iZj6c5lsj0ormpct8ca0qdZ:~# git clone https://github.com/meshplus/goduck.git**
Cloning into 'goduck'...
remote: Enumerating objects: 2343, done.
remote: Counting objects: 100% (820/820), done.
remote: Compressing objects: 100% (349/349), done.
remote: Total 2343 (delta 435), reused 700 (delta 380), pack-reused 1523
Receiving objects: 100% (2343/2343), 37.14 MiB | 13.92 MiB/s, done.
Resolving deltas: 100% (1223/1223), done.
**root@iZj6c5lsj0ormpct8ca0qdZ:~# cd goduck**
**root@iZj6c5lsj0ormpct8ca0qdZ:~/goduck# make install**
cd cmd/goduck && packr
go install -ldflags '-X "github.com/meshplus/goduck.BuildDate=2021-07-28T09:50:54" -X "github.com/meshplus/goduck.CurrentCommit=485459b" -X "github.com/meshplus/goduck.CurrentBranch=master" -X "github.com/meshplus/goduck.CurrentVersion=1.0.0"' ./cmd/goduck
Build goduck successfully!
**root@iZj6c5lsj0ormpct8ca0qdZ:~/goduck# goduck init**
**root@iZj6c5lsj0ormpct8ca0qdZ:~/goduck# goduck bitxhub start**
unsupport BitXHub verison
**root@iZj6c5lsj0ormpct8ca0qdZ:~/goduck# goduck version**
NAME:
   GoDuck version - Components version

USAGE:
   GoDuck version command [command options] [arguments...]

COMMANDS:
   all      All components version
   goduck   Goduck version
   help, h  Shows a list of commands or help for one command

OPTIONS:
   --help, -h  show help (default: false)
**root@iZj6c5lsj0ormpct8ca0qdZ:~/goduck# goduck playground start**
unsupport verison
