### ISSUE TITLE
I cannot build up the bitxhub

### ISSUE THREAD

**Issue by XiaoTXC** [meshplus/bitxhub#723]
### 1. What did you do?

cmd : make build

### 2. What did you expect to see?
it works 
### 3. What did you see instead?
build github.com/meshplus/bitxhub-kit/crypto/asym/ecdsa/secp256k1: cannot load github.com/meshplus/bitxhub-kit/crypto/asym/ecdsa/secp256k1: no Go source files
make: *** [Makefile:68: build] Error 1

### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)
i cannot see

**Comment by jzhe886** [comment]
1.  `go clean -modcache`.
2.  configure the [goproxy](https://goproxy.io/).
3.  please `make build` again.

**Comment by XiaoTXC** [comment]
go: github.com/meshplus/eth-kit@v0.0.0-20210906064541-8dfea98dbf95 requires
	github.com/meshplus/bitxhub-model@v1.2.1-0.20210805020100-41c27414badf: invalid version: unknown revision 41c27414badf
cd internal/repo && packr
rm -f imports/imports.go
GO111MODULE=on go build -ldflags '-X "github.com/meshplus/bitxhub.BuildDate=2021-12-07T15:22:17" -X "github.com/meshplus/bitxhub.CurrentCommit=c9f5d17" -X "github.com/meshplus/bitxhub.CurrentBranch=master" -X "github.com/meshplus/bitxhub.CurrentVersion=dev"' ./cmd/bitxhub
go: github.com/meshplus/eth-kit@v0.0.0-20210906064541-8dfea98dbf95 requires
	github.com/meshplus/bitxhub-model@v1.2.1-0.20210805020100-41c27414badf: invalid version: unknown revision 41c27414badf
make: *** [Makefile:68: build] Error 1
