### ISSUE TITLE
bloom filter caused panic

### ISSUE THREAD

**Issue by 4ever9** [meshplus/bitxhub#8]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead?

![image](https://user-images.githubusercontent.com/29200902/78890949-248c9780-7a99-11ea-91c3-572f3f86453b.png)

### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)

```
$ bitxhub version
BitXHub version: 1.0.0-rc1-master-71e4cd0
App build date: 2020-04-09T19:28:57
System version: darwin/amd64
Golang version: go1.13.8
```

**Comment by jzhe886** [comment]
At the same time, a large number of write bloom filters will cause panic.
close #9
