### ISSUE TITLE
make: *** [install] Error 1

### ISSUE THREAD

**Issue by ITLittleMing** [meshplus/bitxhub#954]
This error occurs when I use the "make build" command to deploy BitXHub. Does anyone know how to solve it?

## General Question
[root@localhost bitxhub]# make build
cd internal/repo && packr
rm -f imports/imports.go
GO111MODULE=on go build -ldflags '-X "github.com/meshplus/bitxhub.BuildDate=2022-12-03T09:39:25" -X "github.com/meshplus/bitxhub.CurrentCommit=f3d0f0d" -X "github.com/meshplus/bitxhub.CurrentBranch=HEAD" -X "github.com/meshplus/bitxhub.CurrentVersion=v1.6.2"' ./cmd/bitxhub
/root/go/pkg/mod/github.com/huin/goupnp@v1.0.1-0.20210310174557-0ca763054c88/httpu/multiclient.go:7:2: missing go.sum entry for module providing package golang.org/x/sync/errgroup (imported by github.com/huin/goupnp/httpu); to add:
	go get github.com/huin/goupnp/httpu@v1.0.1-0.20210310174557-0ca763054c88
make: *** [build] Error 1

**Comment by Karenlrx** [comment]
please give tihe bitxhub version and goVersion

**Comment by xiaochenl** [comment]
Try running the command first `go mod tidy`, and then run `make build`
