### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by treasersimplifies** [meshplus/bitxhub#97]
### 1. What did you do?

Test tps of bitxhub.

### 2. What did you expect to see?

no error

### 3. What did you see instead?

too many open files error

### 4. What version of BitXHub are you using? (`bitxhub version` on BitXHub)

```
BitXHub version: 1.0.0-rc1-master-bedbc5b
App build date: 2020-06-23T20:47:38
System version: darwin/amd64
Golang version: go1.14.4
```

**Comment by treasersimplifies** [comment]
[![bitxhub-too-many-open-files.png](https://i.postimg.cc/tJGXLmG5/bitxhub-too-many-open-files.png)](https://postimg.cc/G8zwDK28)

**Comment by Karenlrx** [comment]
fixed in master

**Comment by treasersimplifies** [comment]
Hi there,Thank you for your email. I am currently offline and will not have access to email instantly. If this is urgent, please contact me by phone 18258583270. I will do my best to respond promptly to your email when I am on line.Best,
